
<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <?php foreach ($list as $item): ?>
            <tr>
                <td>
                    <span><?php echo $item['description'] ?></span>
                    <span class="label label-default pull-right" title="">
                        <?php echo $item['type_abbr'] ?>
                    </span>
                </td>
                <td>
                    <div class="btn-group">
                        <a href="#" class="btn btn-default">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>