
<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('dashboard'); ?>">Dashboard</a></li>
  <li class="active">Templates</li>
</ol>

<div class="row">
    <div class="col-md-6">
        <h3>All templates</h3>
    </div>
    <div class="col-md-6">
        <a href="<?php echo $this->url('dashboard_template', array('action' => 'save')); ?>"
           class="btn btn-primary btn-lg pull-right">
            <i class="fa fa-plus"></i> New Template
        </a>
    </div>
</div>

<hr/>

<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Editor Mode</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <?php foreach ($list as $item): ?>
            <tr>
                <td>
                    <span><?php echo $item['description'] ?></span>
                    <span class="label label-default pull-right" title="">
                        <?php echo $item['type'] ?>
                    </span>
                </td>
                <td>
                    <span class="label label-primary">
                        <?php echo $item['html_editor_mode'] ?>
                    </span>
                </td>
                <td>
                    <div class="btn-group">
                        <a href="<?php echo $this->url('dashboard_template',
                                array(
                                    'action' => 'save',
                                    'id' => $item['id']
                                )); ?>" class="btn btn-default">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>