
<div class="row" style="margin-bottom: 10px;">
    <div class="col-md-12">
        <div class="btn-group">
            <button id="bt-save" onclick="return false;"
                    class="btn btn-primary" rel="tooltip" title="Ctrl+S">
                <i class="fa fa-save"></i> Save
            </button>
            <button id="bt-preview" onclick="return false;"
                    class="btn btn-default" rel="tooltip" title="Ctrl+Shift+V">
                <i class="fa fa-eye"></i> Preview
            </button>
        </div>

        <div class="btn-group">
            <a data-depth="#" href="#" class="btn btn-default bt-header" onclick="return false;"
               rel="tooltip" title="Ctrl+1">
                <b>h1</b>
            </a>
            <a data-depth="##" href="#" class="btn btn-default bt-header" onclick="return false;"
               rel="tooltip" title="Ctrl+2">
                <b>h2</b>
            </a>
            <a data-depth="###" href="#" class="btn btn-default bt-header" onclick="return false;"
               rel="tooltip" title="Ctrl+3">
                <b>h3</b>
            </a>
        </div>

        <div class="btn-group">
            <a id="bt-bold" href="#" class="btn btn-default" onclick="return false;"
               rel="tooltip" title="Ctrl+B">
                <i class="fa fa-bold"></i>
            </a>
            <a id="bt-italic" href="#" class="btn btn-default" onclick="return false;"
               rel="tooltip" title="Ctrl+I">
                <i class="fa fa-italic"></i>
            </a>
        </div>

        <div class="btn-group">
            <!--         <a id="bt-picture" href="#modal-picture" class="btn btn-default" onclick="return false;"
                        role="button" rel="tooltip" title="Ctrl+Shift+P]"
                        data-toggle="modal">
                        <i class="fa fa-picture-o"></i>
                     </a>-->
            <a id="bt-code" href="#" class="btn btn-default" onclick="return false;"
               rel="tooltip" title="Ctrl+Shift+C">
                <i class="fa fa-code"></i>
            </a>
            <a id="bt-link" href="#" class="btn btn-default" onclick="return false;"
               rel="tooltip" title="Ctrl+Shift+L">
                <i class="fa fa-link"></i>
            </a>
        </div>

        <div class="btn-group">
            <a id="bt-undo" href="#" class="btn btn-default" onclick="return false;">
                <i class="fa fa-reply"></i> Undo
            </a>
            <a id="bt-redo" href="#" class="btn btn-default" onclick="return false;">
                <i class="fa fa-share"></i> Redo
            </a>
        </div>

        <div class="btn-group">
            <a id="bt-theme" href="#" class="btn btn-default"
               data-theme="default" data-color="#e8f2ff"
               onclick="return false;"
               rel="tooltip" title="Lighs On">
                <i class="fa fa-lightbulb-o"></i>
            </a>
            <!--         <a href="#" class="btn btn-inverse theme"
                        data-theme="lesser-dark" data-color="#555753"
                        onclick="return false;"
                        rel="tooltip" title="Lighs Off">
                        <i class="fa fa-lightbulb-o"></i>
                     </a>-->
        </div>
        
        <button class="btn btn-info" onclick="TogetherJS(this); return false;"><i class="fa fa-rss"></i> Share</button>
       
    </div>
</div>