<!-- modal link -->
<div class="modal fade" id="modal-link" tabindex="-1" role="dialog" aria-labelledby="modal-link-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-link-label"><?php echo $this->translate('Insert Link'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="url">URL *</label>
                    <input type="url" class="form-control" id="url" placeholder="http://"/>
                </div>
                <div class="form-group">
                    <label for="url"><?php echo $this->translate('Description (Optional)'); ?></label>
                    <input type="text" class="form-control" id="description" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?php echo $this->translate('Close'); ?>
                </button>
                <button type="button" class="btn btn-primary" id="modal-link-bt-ok">
                    <?php echo $this->translate('Ok'); ?>
                </button>
            </div>
        </div>
    </div>
</div>