<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <?php
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
      <div class="form-group">
         <?php echo $this->formRow($form->get('username')); ?>
      </div>
      <div class="form-group">
         <?php echo $this->formRow($form->get('password')); ?>
      </div>
      <div class="form-group">
         <?php echo $this->formRow($form->get('email')); ?>
      </div>
      
      <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
   </div>
</div>