
<div class="row">
   <div class="col-md-8">
      <h4>New Document</h4><hr/>
      <?php
      $form->prepare();
      echo $this->form()->openTag($form);
      ?>
      <div class="form-group">
         <?php echo $this->formRow($form->get('name')); ?>
      </div>
      <div class="form-group">
         <?php echo $this->formLabel($form->get('original_template_id')); ?>
         <?php foreach($form->get('original_template_id')->getValueOptions() as $index => $value): ?>
         <div class="radio">
            <label><input type="radio" name="original_template_id"
                          id="original_template_id"
                          value="<?php echo $index ?>"
                          <?php if ($form->get('original_template_id')->getValue() == $index): ?>
                          checked="checked"
                          <?php endif; ?>
                          ><?php echo $value ?></label>
         </div>
         <?php endforeach; ?>
      </div>
      
      <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
      ?>
   </div>
</div>