<?php
namespace Application;
?>

<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Project Collaby')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/forms.css')
                ->prependStylesheet($this->basePath() . '/css/navbar-fixed-top.css')
                ->prependStylesheet($this->basePath() . '/lib/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/lib/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/lib/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/lib/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/lib/js/jquery-2.0.3.min.js')
        ?>
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">collaby</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">
                                <?php echo $this->translate('Home', __NAMESPACE__) ?></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-file"></i><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('new-document', array('type' => 'latex')) ?>">
												<?php echo $this->translate('Document'); ?>
												</a></li>
                                <li><a href="<?php echo $this->url('new-document', array('type' => 'beamer')) ?>">
												<?php echo $this->translate('Presentation'); ?>
												</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('about') ?>">
                               <?php echo $this->translate('About') ?>
                            </a>
                        </li>
                        <?php $user = $this->session()->offsetGet('user'); ?>
                        <?php if ($user): ?>
                        <li>
                            <a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a>
                        </li>
                        <?php else: ?>
                        <li>
                            <a href="<?php echo $this->url('signup') ?>">
                                <?php echo $this->translate('Signup') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('login') ?>">
                                <?php echo $this->translate('Login') ?>
                            </a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <?=$this->messages()?>
            <!-- Main component for a primary marketing message or call to action -->
            <?php echo $this->content; ?>

            <hr>

            <footer>
                <p>&copy; IFCE <?php echo date("Y") ?></p>
            </footer>
        </div> <!-- /container -->
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
