
<div class="row">
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <img class="fb" src="https://graph.facebook.com/atilacamurca/picture?width=250&height=250">
            <h3>Átila Camurça</h3>
            <p><i class="fa fa-compass"></i> Criador e Líder do Projeto</p>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <img class="fb" src="https://graph.facebook.com/jovane.pires/picture?width=250&height=250">
            <h3>Jovane Pires</h3>
            <p><i class="fa fa-keyboard-o"></i> Desenvolvedor Zend</p>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            <img class="fb" src="https://graph.facebook.com/pericles.henrique.1/picture?width=250&height=250">
            <h3>Péricles Henrique</h3>
            <p><i class="fa fa-keyboard-o"></i> Desenvolvedor Zend</p>
        </div>
    </div>
</div>
</div>